-- lua/plugins/colorscheme.lua
return {
  { "catppuccin/nvim", name = "catppuccin", priority = 1000 },
  { "nordtheme/vim", name = "nord", priority = 1000 },
  { "rakr/vim-one", name = "vim-one", priority = 1000 },
  { "mhartington/oceanic-next", name = "oceanic-next", priority = 1000 },
  { "drewtempelmeyer/palenight.vim", name = "palenight", priority = 1000 },
  { "ayu-theme/ayu-vim", name = "ayu-vim", priority = 1000 },
  { "folke/tokyonight.nvim", name = "tokyonight", priority = 1000 },
  { "Mofiqul/dracula.nvim", name = "dracula", priority = 1000 },
  { "Mofiqul/vscode.nvim", name = "vscode", priority = 1000 },
  { "rose-pine/neovim", name = "rose-pine", priority = 1000 },
  { "atmosuwiryo/vim-winteriscoming", name = "winteriscoming", priority = 1000 },
  { "rebelot/kanagawa.nvim", name = "kanagawa", priority = 1000 },
  { "EdenEast/nightfox.nvim", name = "nightfox", priority = 1000 },
  { "navarasu/onedark.nvim", name = "one-dark", priority = 1000 },
  { "sainnhe/gruvbox-material", name = "gruvbox-material", priority = 1000 },
  { "sainnhe/everforest", name = "everforest", priority = 1000 },
  { "scottmckendry/cyberdream.nvim", name = "cyberdream", priority = 1000 },
  { "sainnhe/sonokai", name = "sonokai", priority = 1000 },
  { "ribru17/bamboo.nvim", name = "bamboo", priority = 1000 },
}
